### ISSUE TITLE
Support for Orphan Mode

### ISSUE THREAD

**Issue by sergio97** [chef-cookbooks/ntp#126]
http://support.ntp.org/bin/view/Support/OrphanMode
Do you have any intention of supporting this? If not, is there a way to put config values directly into NTP's config file using your cookbook?

Orphan mode could replace the "use_cmos" option since orphan mode is now the preferred method for dealing with a disconnect from all authoritative NTP servers (as of NTP version 4).

**Comment by jheung-r7** [comment]
I have added support for orphan mode via PR #140, can you take a look if you get a chance?

**Comment by sergio97** [comment]
Your implementation for orphan mode options looks good.

However, the "use_cmos" option is no longer the recommended way to run NTP without access to a clock source, so ideally the stuff about fudging local clock should be removed (or at least the comments about fudging local clock be updated to explain that it's not best practice anymore).

In an environment with a single NTP server either a locally fudged clock or orphan mode will work, but if you have multiple NTP servers connected in a mesh topology orphan mode is preferred, so it should (and maybe does, I forget) override the local fudging behaviour.

**Comment by tas50** [comment]
This was shipped
