### ISSUE TITLE
Doesn't support RedHat 7 which replaces NTP with chronyd

### ISSUE THREAD

**Issue by MrCyrus** [chef-cookbooks/ntp#141]
If NTP is being configured, then shouldn't this cookbook uninstall (or at least disable/stop) 'chronyd' before enabling/starting NTP?

**Comment by tas50** [comment]
We should probably support at least the disabling of chronyd. Supporting both seems out of the scope of this cookbook.

**Comment by lamont-granquist** [comment]
This feels out of scope.   If users are running ntp on their RHEL7 systems, they should know to stop chronyd.

This cookbook is about managing ntpd, not about managing chronyd.
