### ISSUE TITLE
Doesn't start Centos 7 service as it's now systemd

### ISSUE THREAD

**Issue by carlewis** [chef-cookbooks/ntp#150]
It seems that many services on CentOS 7 have been moved from init.d to systemd. (I suppose it's the same for RHEL 7)
Maybe it would be a good thing to change the service provider in this case: 
```
service node['ntp']['service'] do
  supports status: true, restart: true
  action [:enable, :start]
  timeout 120 if platform_family?('windows')
  retries 3
  retry_delay 5
  provider Chef::Provider::Service::Systemd if node[:platform] == "centos" && node[:platform_version].to_f >= 7.0
end
```
or something like that.

**Comment by tas50** [comment]
Modern chef releases should do this automatically. What version of Chef are you running?

**Comment by shortdudey123** [comment]
`Use Systemd for recent Fedora and RHEL 7.` was part of the `12.0.0` chef release

**Comment by carlewis** [comment]
OK, that was the point (Chef 11), I close the issue. Thanks
