### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by gavit** [chef-cookbooks/ntp#153]
I would expect something as follow to happen on windows instead of having a third party application for a client.

```
w32tm /config /manualpeerlist:"pool.ntp.org" /syncfromflags:MANUAL
Stop-Service w32time
Start-Service w32time
w32tm /resync
w32tm /query /status
```

**Comment by tas50** [comment]
Here's my thoughts (from years ago) on why w32tm isn't the right thing to do.

http://www.therealtimsmith.com/home/2012/09/ntp-on-windows-aka-w32tm-is-garbage/

**Comment by gavit** [comment]
Hi Tim,
Could the NTP cookbook not be updated with a flag to choose between win32tm
and the 3rd party solution? And then config accordingly?
Kind regards,
