### ISSUE TITLE
ntpd doesn't start on Ubuntu 16.04 when ntpdate is installed

### ISSUE THREAD

**Issue by eheydrick** [chef-cookbooks/ntp#154]
There's [a bug](https://bugs.launchpad.net/ubuntu/+source/ntp/+bug/1577596) in Ubuntu 16.04 that prevents ntpd from starting at boot when the `ntpdate` package is installed. The Ubuntu maintainers have suggested not installing `ntpdate`. I'm overriding the ntp packages attribute to not install `ntpdate` and ntpd now starts at boot and everything seems to be working fine. I propose making this the default on Ubuntu 16.04. Thoughts?

**Comment by dustin96080** [comment]
+1

**Comment by tas50** [comment]
This was fixed in the 3.2.0 release
