### ISSUE TITLE
v3.5.1 is not available in the Supermarket

### ISSUE THREAD

**Issue by rbogdany** [chef-cookbooks/ntp#171]
### Cookbook version
3.5.1

I am not sure this is right place for this but when is v3.5.1 going to be released to the Supermarket?

For v3.5.0, it looks to me like it was available same day (June 27th) but v3.5.1 was released 12 days ago now (June 28th) and is still not available via the Supermarket.  I really would like to pull down 3.5.1 since that contains the latest ntp.leapseconds file.

**Comment by tas50** [comment]
It looks like the push failed. I pushed it again. It's up now
