### ISSUE TITLE
ntp.leapseconds file expired 

### ISSUE THREAD

**Issue by rbogdany** [chef-cookbooks/ntp#182]
### Cookbook version
3.6.2

### Chef-client version
14.11.21

### Platform Details
RHEL 7.6

### Scenario:
ntp.leapseconds file expired on 28 June 2019

### Steps to Reproduce:
Just converge with this cookbook

### Expected Result:
A non-expired ntp.leapseconds file.  A version that expires 28 Dec 2019 is available [here](https://www.ietf.org/timezones/data/leap-seconds.list).  Would it be prudent to just change the cookbook_file resource that lays down the leap seconds file to just be a remote_file that points to https://www.ietf.org/timezones/data/leap-seconds.list???  We wouldn't have to update things every 6 months this way.

### Actual Result:
ntp.leapseconds file expired on 28 June 2019

**Comment by tas50** [comment]
We don't use the remote file here since that would take down the ietf.org server with requests from chef clients. Unfortunately we're sort of stuck in a world where we have to update files. I've updated things to the latest.
